### ISSUE TITLE
Some API function should be class const

### ISSUE THREAD

**Issue by guilhembn** [sarthou/ontologenius#12]
I think some API function should be const : 
e.g. `std::vector<std::string> getUp(const std::string& name, int depth = -1, const std::string& selector = "");` will not modify the ontology, so maybe it shoud be good to put it const ?

**Comment by sarthou** [comment]
Because the ontologenius API is based on ros::ServiceClient that does not have a const call function, this change is not possible.
http://docs.ros.org/indigo/api/roscpp/html/classros_1_1ServiceClient.html
